/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== Blue.qrc ==================
static const unsigned char temp_binary_data_0[] =
"<!DOCTYPE RCC><RCC version=\"1.0\">\n"
"<qresource>\n"
"<file>Blue.qss</file>\n"
"</qresource>\n"
"</RCC>\n";

const char* Blue_qrc = (const char*) temp_binary_data_0;

//================== Blue.qss ==================
static const unsigned char temp_binary_data_1[] =
"QPushButton{\n"
"min-width : 80px;\n"
"border: 2px solid grey;\n"
"border-radius: 6px;\n"
"margin-top: 1ex;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #811453, stop: 1 #702963);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px solid orange;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: orange;\n"
"border-color: grey;\n"
"}\n"
"\n"
"QGroupBox{\n"
"subcontrol: .QGroupBox;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #003366, stop: 1 #22427C);\n"
"margin-top: 3ex;\n"
"border-radius: 5px;\n"
"font-size: 10pt;\n"
"font-weight: bold;\n"
"color: white;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px;\n"
"color: white;\n"
"}\n"
"\n"
"QMainWindow, QDialog{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #003366, stop: 1 #22427C);\n"
"border-radius: 5px;\n"
"margin-top: 3ex;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: white;\n"
"}  \n"
"\n"
"QPlainTextEdit, QTextEdit{\n"
"background-color: transparent;\n"
"border: 2px solid #702963;\n"
"border-radius: 5px;\n"
"top: 3px;\n"
"margin-top: 3ex;\n"
"font-size:12pt;\n"
"font-weight:bold;\n"
"color: white;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #003366, stop: 1 #22427C);\n"
"\tcolor: white;\n"
"}\n"
"    \n"
"QTextBrowser:document{\n"
"\ttext-decoration: underline;\n"
"\tcolor: white;\n"
"\tfont: Menlo;\n"
"\tfont-size: 14px\n"
"}\n"
"\n"
"QLabel{\n"
"color : white;\n"
"background: transparent;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; \n"
"left: 13px; right: 13px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"height: 40px;\n"
"width: 30px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #AAAAAA, stop : 0.05 #0A0A0A, stop: 0.3 #101010, stop : 0.90 #AAAAAA, stop: 0.91 #000000);\n"
"margin: 0 -5px;\n"
"border-radius: 5px;\n"
"} \n"
"\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 yellow, stop : 0.5 orange);\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"background: grey;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"background: red;\n"
"position: absolute;\n"
"top: 14px; bottom: 14px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 40px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #6A455D, stop : 0.05 #811453, stop: 0.3 #811453, stop : 0.90 #6A455D, stop: 0.91 #702963);\n"
"margin: -5px 0;\n"
"border-radius: 5px;\n"
"}\n"
"    \n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 yellow, stop : 0.5 orange);\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: grey;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"color : white;\n"
"border-top: 2px #702963;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 1.0 #22427C);\n"
"}\n"
"    \n"
"QTabWidget::tab-bar {\n"
"left: 5px;\n"
"}\n"
"    \n"
"QTabBar::tab {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 0.4 #22427C, stop: 0.5 #003366, stop: 1.0 #22427C);\n"
"border: 2px solid #808080;\n"
"color : white;\n"
"border-bottom-color: #702963;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"min-width: 8ex;\n"
"padding: 2px;\n"
"}\n"
"    \n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 0.4 #22427C, stop: 0.5 #003366, stop: 1.0 #22427C);\n"
"color : white;\n"
"}\n"
"    \n"
"QTabBar::tab:selected {\n"
"color : white;\n"
"border-color: #702963;\n"
"border-bottom-color: #22427C;\n"
"}\n"
"    \n"
"QTabBar::tab:!selected {\n"
"margin-top: 2px;\n"
"}\n"
"\n"
"QListWidget{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QListWidget::item{                \n"
"\tcolor: white;\n"
"}\n"
"\n"
"QStatusBar{\n"
"\tbackground-color: transparent;\n"
"\tborder: 0px; \n"
"\tpadding:0px 0px 0px 0px; \n"
"\tmargin:0px;\n"
"}\n"
"\n"
"QScrollArea > QWidget > QWidget{\n"
"\tbackground: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 0.4 #22427C, stop: 0.5 #003366, stop: 1.0 #22427C);\n"
"}\n"
"\n"
"QScrollArea > QWidget {\n"
"\tbackground: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 0.4 #22427C, stop: 0.5 #003366, stop: 1.0 #22427C);\n"
"}\n"
"\n"
"QScrollArea {\n"
"\tbackground: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #003366, stop: 0.4 #22427C, stop: 0.5 #003366, stop: 1.0 #22427C);\n"
"}";

const char* Blue_qss = (const char*) temp_binary_data_1;

//================== Default.qrc ==================
static const unsigned char temp_binary_data_2[] =
"<!DOCTYPE RCC><RCC version=\"1.0\">\n"
"<qresource>\n"
"<file>Default.qss</file>\n"
"</qresource>\n"
"</RCC>\n";

const char* Default_qrc = (const char*) temp_binary_data_2;

//================== Default.qss ==================
static const unsigned char temp_binary_data_3[] =
"QPushButton{\n"
"min-width : 80px;\n"
"border: 2px solid grey;\n"
"border-radius: 6px;\n"
"margin-top: 1ex;\n"
"border-color: #811453;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 2px;\n"
"border-radius: 6px;\n"
"border-color: #811453;\n"
"background-color: #6A455D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #6A455D;\n"
"border-radius: 6px;\n"
"border-color: #811453;\n"
"}\n"
"\n"
"QGroupBox{\n"
"subcontrol: .QGroupBox;\n"
"margin-top: 3ex;\n"
"font-size: 10pt;\n"
"font-weight: bold;\n"
"color: black;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px;\n"
"color: black;\n"
"}\n"
"\n"
"QMainWindow {\n"
"margin-top: 3ex;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: black;\n"
"}\n"
"\n"
"QPlainTextEdit, QTextEdit{\n"
"background-color: transparent;\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"top: 3px;\n"
"margin-top: 3ex;\n"
"font-size:12pt;\n"
"font-weight:bold;\n"
"color: black;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"color: black;\n"
"}\n"
"QTextBrowser:document{\n"
"text-decoration: underline;\n"
"color: black;\n"
"font: Menlo;\n"
"font-size: 14px\n"
"}\n"
"\n"
"QLabel{\n"
"color : black;\n"
"background: transparent;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute; \n"
"left: 13px; right: 13px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"height: 40px;\n"
"width: 30px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #E67E30, stop : 0.05 #AD4F09, stop: 0.3 #E67E30, stop : 0.90 #AD4F09, stop: 0.91 #AD4F09);\n"
"margin: 0 -5px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"stop: 0 #6A455D, stop : 0.5 #6A455D);\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"background: grey;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"background: red;\n"
"position: absolute;\n"
"top: 14px; bottom: 14px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 40px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #E67E30, stop : 0.05 #AD4F09, stop: 0.3 #E67E30, stop : 0.90 #AD4F09, stop: 0.91 #AD4F09);\n"
"margin: -5px 0;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6A455D, stop : 0.5 #6A455D);\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: grey;\n"
"}\n"
"\n"
"QListWidget{\n"
"background-color: transparent;\n"
"}";

const char* Default_qss = (const char*) temp_binary_data_3;

//================== Grey.qrc ==================
static const unsigned char temp_binary_data_4[] =
"<!DOCTYPE RCC><RCC version=\"1.0\">\n"
"<qresource>\n"
"<file>Grey.qss</file>\n"
"</qresource>\n"
"</RCC>\n";

const char* Grey_qrc = (const char*) temp_binary_data_4;

//================== Grey.qss ==================
static const unsigned char temp_binary_data_5[] =
"QPushButton {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0.8, y2: 0.8,\n"
"stop: 0 #B0B0B0, stop: 1 #404040);\n"
"min-width : 80px;\n"
"border: 2px solid grey;\n"
"border-radius: 6px;\n"
"margin-top: 1ex;\n"
"color:white\n"
"}\n"
"    \n"
"QPushButton:hover {\n"
"border: 2px solid orange;\n"
"}\n"
"    \n"
"QPushButton:pressed {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #404040, stop: 1 #B0B0B0);\n"
"}\n"
"    \n"
"QGroupBox {\n"
"subcontrol: .QGroupBox\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"margin-top: 3ex;\n"
"border-radius: 5px;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: white;\n"
"}\n"
"    \n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px;\n"
"color : white;\n"
"}\n"
"\n"
"QMainWindow, QDialog {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"border-radius: 5px;\n"
"margin-top: 3ex;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: white;\n"
"}    \n"
"    \n"
"QPlainTextEdit, QTextEdit{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"border-color: yellow;\n"
"border-radius: 5px;\n"
"top: 3px;\n"
"margin-top: 3ex;\n"
"font-size:12pt;\n"
"font-weight:bold;\n"
"color: white;\n"
"}\n"
"    \n"
"QTextBrowser {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0.8, y2: 0.8, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"color: white;\n"
"}\n"
"    \n"
"QTextDocument{\n"
"text-decoration: underline;\n"
"color: white;\n"
"font: Menlo;\n"
"font-size: 14px\n"
"}\n"
"\n"
"QLabel{\n"
"\tcolor : white;\n"
"\tbackground: transparent;\n"
"}\n"
"    \n"
"QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute;\n"
"left: 13px; right: 13px;\n"
"}\n"
" \n"
"QSlider::handle:vertical {\n"
"height: 40px;\n"
"width: 30px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #AAAAAA, stop : 0.05 #0A0A0A, stop: 0.3 #101010, stop : 0.90 #AAAAAA, stop: 0.91 #000000);\n"
"margin: 0 -5px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 yellow, stop : 0.5 orange);\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"background: grey;\n"
"}\n"
"    \n"
"QSlider::groove:horizontal {\n"
"background: red;\n"
"position: absolute;\n"
"top: 14px; bottom: 14px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 40px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #AAAAAA, stop : 0.05 #0A0A0A, stop: 0.3 #101010, stop : 0.90 #AAAAAA, stop: 0.91 #000000);\n"
"margin: -5px 0;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 yellow, stop : 0.5 orange);\n"
"}\n"
"    \n"
"QSlider::add-page:horizontal {\n"
"background: grey;\n"
"}\n"
"    \n"
"QTabWidget::pane {\n"
"border-top: 2px solid orange;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 5px;\n"
"}\n"
"        \n"
"QTabBar::tab {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #909090, stop: 0.4 #888888, stop: 0.5 #808080, stop: 1.0 #909090);\n"
"border: 2px solid #808080;\n"
"border-bottom-color: orange;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"min-width: 8ex;\n"
"padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #D0D0D0, stop: 0.4 #A0A0A0, stop: 0.5 #808080, stop: 1.0 #A0A0A0);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"border-color: orange;\n"
"border-bottom-color: #A0A0A0;\n"
"}\n"
"    \n"
"QTabBar::tab:!selected {\n"
"margin-top: 2px;\n"
"}\n"
"    \n"
"QListWidget{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QListWidget::item{                \n"
"\tcolor: white;\n"
"}\n"
"\n"
"QStatusBar{\n"
"\tbackground-color: transparent;\n"
"\tborder: 0px; \n"
"\tpadding:0px 0px 0px 0px; \n"
"\tmargin:0px;\n"
"}\n"
"\n"
"QScrollArea > QWidget > QWidget{\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 0.8, y2: 0.8, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"}\n"
"\n"
"QScrollArea > QWidget {\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 0.8, y2: 0.8, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"}\n"
"\n"
"QScrollArea {\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 0.8, y2: 0.8, stop: 0 #A0A0A0, stop: 1 #202020);\n"
"}";

const char* Grey_qss = (const char*) temp_binary_data_5;

//================== Salmon.qrc ==================
static const unsigned char temp_binary_data_6[] =
"<!DOCTYPE RCC><RCC version=\"1.0\">\n"
"<qresource>\n"
"<file>Salmon.qss</file>\n"
"</qresource>\n"
"</RCC>\n";

const char* Salmon_qrc = (const char*) temp_binary_data_6;

//================== Salmon.qss ==================
static const unsigned char temp_binary_data_7[] =
"QPushButton{\n"
"background-color:#FF5E4D;\n"
"min-width : 80px;\n"
"border: 2px solid grey;\n"
"border-radius: 6px;\n"
"margin-top: 1ex;\n"
"}\n"
"    \n"
"QPushButton:hover{\n"
"border: 2px ;\n"
"}\n"
"    \n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFE4C4, stop: 1 #FEC3AC);\n"
"}\n"
"\n"
"QGroupBox{\n"
"subcontrol: .QGroupBox\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4, stop: 1 #FEC3AC);\n"
"border-radius: 5px;\n"
"margin-top: 3ex;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: dark grey;\n"
"color: white;\n"
"}\n"
"    \n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center;\n"
"padding: 0 5px;\n"
"color: black;\n"
"}\n"
"    \n"
"QMainWindow, QDialog {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"border-radius: 5px;\n"
"margin-top: 3ex;\n"
"font-size:10pt;\n"
"font-weight:bold;\n"
"color: dark grey;\n"
"color: white;\n"
"}\n"
"    \n"
"QPlainTextEdit, QTextEdit {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"top: 3px;\n"
"margin-top: 3ex;\n"
"font-size:12pt;\n"
"font-weight:bold;\n"
"color: black;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"color: black;\n"
"}\n"
"    \n"
"QTextBrowser:document{\n"
"text-decoration: underline;\n"
"color: white;\n"
"font: Menlo;\n"
"font-size: 14px\n"
"}\n"
"      \n"
"QLabel{\n"
"\tcolor : black;\n"
"\tbackground: transparent;\n"
"}\n"
"  \n"
"QSlider::groove:vertical {\n"
"background: red;\n"
"position: absolute;\n"
"left: 13px; right: 13px;\n"
"}\n"
"    \n"
"QSlider::handle:vertical {\n"
"height: 40px;\n"
"width: 30px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #4E3D28, stop : 0.05 #856D4D, stop: 0.1 #4E3D28, stop : 0.15 #856D4D, stop: 0.2 #4E3D28, stop : 0.25 #856D4D, stop: 0.3 #4E3D28, stop : 0.35 #856D4D, stop: 0.4 #4E3D28, stop : 0.45 #856D"
"4D, stop: 0.5 #4E3D28, stop : 0.55 #856D4D, stop: 0.6 #4E3D28, stop : 0.65 #856D4D, stop: 0.7 #4E3D28, stop : 0.75 #856D4D, stop: 0.8 #4E3D28, stop : 0.85 #856D4D, stop: 0.95 #4E3D28);\n"
"margin: 0 -5px;\n"
"border-radius: 5px;\n"
"}\n"
"    \n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #FF5E4D, stop : 0.5 #FF5E4D);\n"
"}\n"
"    \n"
"QSlider::sub-page:vertical {\n"
"background: #CECECE;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"background: red;\n"
"position: absolute;\n"
"top: 14px; bottom: 14px;\n"
"}\n"
"    \n"
"QSlider::handle:horizontal {\n"
"width: 40px;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #4E3D28, stop : 0.05 #856D4D, stop: 0.1 #4E3D28, stop : 0.15 #856D4D, stop: 0.2 #4E3D28, stop : 0.25 #856D4D, stop: 0.3 #4E3D28, stop : 0.35 #856D4D, stop: 0.4 #4E3D28, stop : 0.45 #856D"
"4D, stop: 0.5 #4E3D28, stop : 0.55 #856D4D, stop: 0.6 #4E3D28, stop : 0.65 #856D4D, stop: 0.7 #4E3D28, stop : 0.75 #856D4D, stop: 0.8 #4E3D28, stop : 0.85 #856D4D, stop: 0.95 #4E3D28);\n"
"margin: -5px 0;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FF5E4D stop : 0.5 #FF5E4D);\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #CECECE;\n"
"}\n"
"    \n"
"QTabWidget::pane {\n"
"color : black;\n"
"border-top: 2px #FF5E4D;\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 5px;\n"
"}\n"
"    \n"
"QTabBar::tab {\n"
"background: #FFE4C4;\n"
"border: 2px solid #FF5E4D;\n"
"color : black;\n"
"border-bottom-color: #FF5E4D;\n"
"border-top-left-radius: 4px;\n"
"border-top-right-radius: 4px;\n"
"min-width: 8ex;\n"
"padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"background: #FEC3AC;\n"
"color : white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"margin-top: 2px;\n"
"}\n"
"    \n"
"QListWidget{     \n"
"background-color: transparent;\n"
"}\n"
"\n"
"QListWidget::item{                \n"
"\tcolor: color;\n"
"}\n"
"\n"
"QStatusBar{\n"
"\tbackground-color: transparent;\n"
"\tborder: 0px; \n"
"\tpadding:0px 0px 0px 0px; \n"
"\tmargin:0px;\n"
"}\n"
"\n"
"QScrollArea > QWidget > QWidget{\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"}\n"
"\n"
"QScrollArea > QWidget {\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"}\n"
"\n"
"QScrollArea {\n"
"\tbackground-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #FFE4C4,stop: 1 #FEC3AC);\n"
"}";

const char* Salmon_qss = (const char*) temp_binary_data_7;


const char* getNamedResource (const char*, int&) throw();
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes) throw()
{
    unsigned int hash = 0;
    if (resourceNameUTF8 != 0)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0xe691bd1d:  numBytes = 88; return Blue_qrc;
        case 0xe691bd4c:  numBytes = 3901; return Blue_qss;
        case 0x49635b44:  numBytes = 91; return Default_qrc;
        case 0x49635b73:  numBytes = 2078; return Default_qss;
        case 0x11294d22:  numBytes = 88; return Grey_qrc;
        case 0x11294d51:  numBytes = 3895; return Grey_qss;
        case 0x7e68d131:  numBytes = 90; return Salmon_qrc;
        case 0x7e68d160:  numBytes = 4125; return Salmon_qss;
        default: break;
    }

    numBytes = 0;
    return 0;
}

const char* namedResourceList[] =
{
    "Blue_qrc",
    "Blue_qss",
    "Default_qrc",
    "Default_qss",
    "Grey_qrc",
    "Grey_qss",
    "Salmon_qrc",
    "Salmon_qss"
};

}
